### ISSUE TITLE
Finalize `arlas-subscriptions` chart

### ISSUE THREAD

**Issue by elouanKeryell-Even** [gisaia/ARLAS-subscriptions#97]
Follow up to #90

# TODO

# Additional tasks

- [x] Update images' version
- [x] Add probes
- [x] Add `imagePullSecret` to each and every container
- [x] Add distinct labels for sub-components
- [x] Add `arlas-subscriptions` in components' names
- [x] Document prerequisites to README (create elasticsearch index, etc etc...)
- [x] Document docker images used

---

## Kubernetes probes

| | liveness | readiness |
|-|-|-|
| arlas-server | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true<br/>- elasticsearch.healthy == true |
| subscription-manager | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true<br/>- elasticsearch.healthy == true<br/>- mongo.healthy == true |
| subscription-matcher | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true | `/admin/healthcheck`<br/>- HTTP code 200<br/>- deadlocks.healthy == true |

## Notable parameters that should be configurable

- subscription-manager: base path for the REST API.
- susbscription-matcher: kafka topics
- all components: log level

### Pre-install

We will not use pre-install hooks.

Pre-install operations rely on back-ends. In the specific case where the user aggregates the chart in an umbrella chart which also deploys the back-ends, back-ends will not be available at the post-install step of the Helm Hooks lifecycle.

Instead, we are going to use initContainers, to do per-component pre-install. This way, a component can wait for its back-ends to be ready before performing operations.

### Post-install

- [best effort] if subscriptions index exists but does not match payload, update it
- [best effort] if subscriptions collection exists but does not match payload, update it

### Post-upgrade

- [best effort] if subscriptions index exists but does not match payload, update it
- [best effort] if subscriptions collection exists but does not match payload, update it
- [best effort]  [disabled by default] if input kafka topic exists but with an insufficient number of partition (see note below), increase its number of partitions as desired. This is to manage case where a helm upgrade upgrades the number of instances of subscription-manager.

### Matcher

- [disabled by default] if input kafka topic does not exist, create it (see note below for number of partitions)
- [disabled by default] if input kafka topic exists but with an insufficient number of partition (see note below), increase its number of partitions as desired
- [disabled by default] if output kafka topic does not exist, create it

## Note on number of partitions for Kafka input topic

Since it is required, with Kafka, to have at least 1 partition per reader, number of partition for the input topic should be at least equal to the number of instances of `subscription-matcher`.

**Comment by elouanKeryell-Even** [comment]
Implemented in https://github.com/gisaia/ARLAS-subscriptions/pull/141
